
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MaintenanceLog extends javax.swing.JFrame {
      private String username;
    /**
     * Creates new form MaintenanceLog
     */
    public MaintenanceLog() {
        initComponents();
        loggedin.setText(loggedin.getText()+username);
        staffid1.setEnabled(false);
        date1.setEnabled(false);
        desc1.setEnabled(false);
        vid1.setEnabled(false);
        Edit.setEnabled(false);
    }

     public MaintenanceLog(String s){
       
        initComponents();
        username=s;
        loggedin.setText(loggedin.getText()+username);
        staffid1.setEnabled(false);
        date1.setEnabled(false);
        desc1.setEnabled(false);
        vid1.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        staffid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        vid1 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc1 = new javax.swing.JTextArea();
        staffid1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Logno1 = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Logno2 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        loggedin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("Maintenance Log");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Staff Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 31, -1, -1));
        jPanel1.add(staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 28, 166, -1));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 63, -1, -1));

        jLabel3.setText("Description");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 81, -1, -1));

        jLabel4.setText("Vehicle Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 186, -1, -1));
        jPanel1.add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 180, 166, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 229, 166, -1));

        jLabel6.setText("Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 232, 36, -1));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 292, -1, -1));

        jTabbedPane1.addTab("New Log", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Staff Id");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 91, -1, -1));

        jLabel8.setText("Description");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 254, -1, -1));

        jLabel9.setText("Vehicle Id");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 196, -1, -1));

        jLabel10.setText("Date");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 145, 36, -1));

        Edit.setText("Update");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel2.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 351, -1, -1));
        jPanel2.add(vid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 190, 137, -1));
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 142, 137, -1));

        desc1.setColumns(20);
        desc1.setRows(5);
        jScrollPane2.setViewportView(desc1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 228, 137, -1));
        jPanel2.add(staffid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 88, 137, -1));

        jLabel11.setText("Log Number");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 14, -1, -1));
        jPanel2.add(Logno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 11, 137, -1));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 47, -1, -1));

        jTabbedPane1.addTab("Edit Log", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Log Number");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanel3.add(Logno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 137, -1));

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jTabbedPane1.addTab("Delete Log", jPanel3);

        loggedin.setText("Logged In As:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(106, 106, 106)
                                .addComponent(loggedin))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton1)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedin)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
         try
        {
            Connection c=MyConnection.createCon();
            PreparedStatement p=c.prepareStatement("insert into maintenancelog(v_no,log_date,description,staff_id) values(?,?,?,?);");
            p.setString(1, vid.getText().trim());
            p.setString(2, date.getText().trim());
            p.setString(3, desc.getText());
            p.setString(4, staffid.getText().trim());
            int rows=p.executeUpdate();
            if(rows==0)
            throw new Exception("Failed!");
            else
            {
                Statement p1=c.createStatement();
                ResultSet rr=p1.executeQuery("select max(log_no) from maintenancelog");
                rr.next();
                String ss=rr.getString(1);
                JOptionPane.showMessageDialog(null,"New log added,Your log number is:"+ss );
            }
        }
        catch(Exception e)
        {
            if(e.getMessage().substring(0, 6).equals("Cannot"))
              JOptionPane.showMessageDialog(null, "No Such Staff Id or Vehicle Id exists");
            else
            JOptionPane.showMessageDialog(null, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        try
        {

            Connection c=MyConnection.createCon();

            PreparedStatement p=c.prepareStatement("update maintenancelog set staff_id=?,v_no=?,description=?,log_date=? where log_no=?");
            p.setString(2, vid1.getText().trim());
            p.setString(4, date1.getText().trim());
            p.setString(3, desc1.getText());
            p.setString(1, staffid1.getText().trim());
            p.setString(5,Logno1.getText().trim());
            int rows=p.executeUpdate();
            if(rows==0)
            throw new Exception("Failed!");
            else
            JOptionPane.showMessageDialog(null,"Updated" );
        }
        catch(Exception e)
        {
            
            if(e.getMessage().substring(0, 6).equals("Cannot"))
              JOptionPane.showMessageDialog(null, "No Such Staff Id or Vehicle Id exists");
            else
            JOptionPane.showMessageDialog(null, e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
      try
      {
          Connection cc=MyConnection.createCon();
            PreparedStatement st=cc.prepareStatement("select staff_id,log_date,description,v_no from maintenancelog where log_no=?;");
            st.setString(1, Logno1.getText().trim());
            ResultSet res=st.executeQuery();
            if(res.next()==false)
            throw new Exception("Not found!!");  
            staffid1.setEnabled(true);
            date1.setEnabled(true);
             desc1.setEnabled(true);
             vid1.setEnabled(true);
            Edit.setEnabled(true);
            staffid1.setText(res.getString(1));
            date1.setText(res.getString(2));
            desc1.setText(res.getString(3));
            vid1.setText(res.getString(4));
     }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try
        {
            Connection c=MyConnection.createCon();
            PreparedStatement p1=c.prepareStatement("select * from maintenancelog where log_no=?");
            p1.setString(1, Logno2.getText().trim());
            ResultSet rr=p1.executeQuery();
            if(rr.next()==false)
            throw new Exception("Not Found!!");
            PreparedStatement p2=c.prepareStatement("delete from partsused where log_no=?");
            PreparedStatement p3=c.prepareStatement("delete from maintenancedetail where log_no=?");
            PreparedStatement p=c.prepareStatement("delete from maintenancelog where log_no=?");
            p2.setString(1, Logno2.getText().trim());
            p3.setString(1, Logno2.getText().trim());
            p.setString(1, Logno2.getText().trim());
            p2.executeUpdate();
            p3.executeUpdate();
            int rows=p.executeUpdate();
            if(rows==0)
            throw new Exception("Failed!");
            else
            JOptionPane.showMessageDialog(null,"Deleted" );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Homepage hm=new Homepage(username);
              hm.setLocationRelativeTo(null);
              hm.setVisible(true);
              dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintenanceLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintenanceLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintenanceLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintenanceLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaintenanceLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Logno1;
    private javax.swing.JTextField Logno2;
    private javax.swing.JButton Search;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextArea desc1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel loggedin;
    private javax.swing.JTextField staffid;
    private javax.swing.JTextField staffid1;
    private javax.swing.JButton submit;
    private javax.swing.JTextField vid;
    private javax.swing.JTextField vid1;
    // End of variables declaration//GEN-END:variables
}
