
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MaintenanceDetails extends javax.swing.JFrame {
        DefaultTableModel tm=null;
        String username;
    /**
     * Creates new form MaintenanceDetails
     */
    public MaintenanceDetails() {
       
       initComponents();
        
        tm=new DefaultTableModel();
        table1.setModel(tm);
        tm.setColumnCount(2);
        Object[] obj={"Part ID","Quantity"};
        tm.setColumnIdentifiers(obj);
        logno.setEditable(false); 
        addnew.setEnabled(false);
        update.setEnabled(false);
        newpart.setEnabled(false);
        qty.setEnabled(false);
        add.setEnabled(false);
        mtype.setEnabled(false);
        delrow.setEnabled(false);
        staffid.setEditable(false);
    }
    public MaintenanceDetails(String s)
    {
        initComponents();
        tm=new DefaultTableModel();
        table1.setModel(tm);
        tm.setColumnCount(2);
        Object[] obj={"Part ID","Quantity"};
        tm.setColumnIdentifiers(obj);
        username=s;
        loggedin.setText(loggedin.getText()+username);
        logno.setEditable(false); 
        addnew.setEnabled(false);
        update.setEnabled(false);
        newpart.setEnabled(false);
        qty.setEnabled(false);
        add.setEnabled(false);
        mtype.setEnabled(false);
        delrow.setEnabled(false);
        staffid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp = new javax.swing.ButtonGroup();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        logno = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        loggedin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newpart = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        added = new javax.swing.JLabel();
        update = new javax.swing.JRadioButton();
        addnew = new javax.swing.JRadioButton();
        delrow = new javax.swing.JButton();
        delrec = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        staffid = new javax.swing.JTextField();
        mtype = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 380, 340));

        jLabel1.setText("Log Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 44, -1, -1));

        logno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lognoFocusLost(evt);
            }
        });
        getContentPane().add(logno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, -1));

        search.setText("Search/Add");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        loggedin.setText("Logged In As:");
        getContentPane().add(loggedin, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 11, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel4.setText("Part Id");

        jLabel5.setText("Quantity");

        btngrp.add(update);
        update.setText("Update And Existing Part");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        btngrp.add(addnew);
        addnew.setText("Add a new part");
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(added, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addnew)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newpart, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(addnew)
                .addGap(17, 17, 17)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(newpart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(added, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 210));

        delrow.setText("Delete Selected Row");
        delrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delrowActionPerformed(evt);
            }
        });
        getContentPane().add(delrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 180, -1));

        delrec.setText("Delete Record");
        delrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delrecActionPerformed(evt);
            }
        });
        getContentPane().add(delrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Maintnance Type");

        jLabel3.setText("Staff_ID");

        mtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(staffid, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(mtype, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 310, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Homepage hm=new Homepage(username);
              hm.setLocationRelativeTo(null);
              hm.setVisible(true);
              dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void delrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delrecActionPerformed
        try
        {
            short f=0;
            Connection c=MyConnection.createCon();
            PreparedStatement p1=c.prepareStatement("select * from maintenancedetail where log_no=?");
            PreparedStatement p2=c.prepareStatement("select * from partsused where log_no=?");
            PreparedStatement p=c.prepareStatement("delete from  maintenancelog where log_no=?");
            PreparedStatement p3=c.prepareStatement("delete from  partsused where log_no=?");
             p.setString(1, logno.getText().trim());
             p1.setString(1, logno.getText().trim());
             p2.setString(1, logno.getText().trim());
             p3.setString(1, logno.getText().trim());
            ResultSet r=p1.executeQuery();
            if(!r.next())
            {
                throw new Exception("not found");
            }
            int rows=p.executeUpdate();
            if(rows==0)
               throw new Exception("No Such log number");
            else
                f=1;
            
            ResultSet res=p1.executeQuery();
            if(res.next())
            {
               rows=p3.executeUpdate();
            }
            
            if(f==1)
            {
             logno.setText("");
             JOptionPane.showMessageDialog(null, "Deleted");
             staffid.setText("");
             mtype.setText("");
             while (tm.getRowCount()>0)
              {
               tm.removeRow(0);
              }
            }
            else
                throw new Exception("failed");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_delrecActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
         try
      {
          newpart.setText("");
          qty.setText("");
          while (tm.getRowCount()>0)
          {
             tm.removeRow(0);
          }
          Connection cc=MyConnection.createCon();
            PreparedStatement st=cc.prepareStatement("select m_type,staff_id from maintenancelog where log_no=?;");
             st.setString(1, logno.getText().trim());
            ResultSet res=st.executeQuery();
            if(!res.next())
            throw new Exception("There is no such registered log number,please register through maintenance log "); 
            mtype.setText(res.getString(1));
            staffid.setText(res.getString(2));
            addnew.setEnabled(true);
            update.setEnabled(true);
            newpart.setEnabled(true);
            qty.setEnabled(true);
            add.setEnabled(true);
            addnew.setSelected(true);
            PreparedStatement st2=cc.prepareStatement("select * from maintenancedetail where log_no=?;");
             st2.setString(1, logno.getText().trim());
            ResultSet res2=st2.executeQuery();
            if(!res2.next())
            {
                PreparedStatement st3=cc.prepareStatement("Insert into maintenancedetail values(?,?,?)");
                st3.setString(2, logno.getText().trim());
                st3.setString(1, staffid.getText().trim());
                st3.setString(3, mtype.getText());
                
                int row=st3.executeUpdate();
                if(row==0)
                    JOptionPane.showMessageDialog(null, "Some error occured while adding!");
            }
            PreparedStatement st1=cc.prepareStatement("select * from partsused where log_no=?;");
             st1.setString(1, logno.getText().trim());
            ResultSet res1=st1.executeQuery();
            if(!res1.next())
            throw new Exception("this log number added\nNo part has been added for this log number,please add!"); 
            do
            {
               tm.addRow(new Object[]{res1.getString(2),res1.getString(3)});
            }while(res1.next());
           
     }
        catch(Exception e)
        {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int i=table1.getSelectedRow();
        update.setSelected(true);
        
            newpart.setText(tm.getValueAt(i, 0).toString());
            qty.setText(tm.getValueAt(i, 1).toString());
       
          delrow.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       update.setSelected(false);
       addnew.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void delrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delrowActionPerformed
       try{
           int i=table1.getSelectedRow();
          if(i==-1)
             throw new Exception("Please select a row");
          
          add.setText("Add");
          newpart.setText("");
          qty.setText("");
           Connection cc=MyConnection.createCon();
            
                PreparedStatement st=cc.prepareStatement("delete from partsused where part_no=? and log_no=? and qty=?");
                st.setString(1,tm.getValueAt(i, 0).toString() );
                st.setString(2, logno.getText().trim());
                st.setString(3,tm.getValueAt(i, 1).toString() );
                int row=st.executeUpdate();
                if(row==0)
                   throw new Exception("Some error occured!");
                JOptionPane.showMessageDialog(null, "deleted");
                tm.removeRow(i);// TODO add your handling code here:
            } 
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,"ss"+ e.getMessage());  
            }
    }//GEN-LAST:event_delrowActionPerformed

    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed
        add.setText("Add");
        newpart.setText("");
        qty.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_addnewActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        add.setText("Update");
        newpart.setText("");
        qty.setText(""); 
        int i=table1.getSelectedRow();
        if(i==-1)
        JOptionPane.showMessageDialog(null, "select the row to be updated from the table");
        else
        {
            newpart.setText(tm.getValueAt(i, 0).toString());
            qty.setText(tm.getValueAt(i, 1).toString());
        }// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        newpart.setText("");
        qty.setText("");
        logno.setEditable(true);
        staffid.setText("");
        mtype.setText("");
        int i=tm.getRowCount();
        while(i-1>=0)
        {
           tm.removeRow(i-1);
           i--;
        }
        added.setText("");
        addnew.setEnabled(false);
        update.setEnabled(false);
        newpart.setEnabled(false);
        qty.setEnabled(false);
        add.setEnabled(false);
        mtype.setEnabled(false);
        delrow.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void lognoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lognoFocusLost
       logno.setEditable(false); // TODO add your handling code here:
    }//GEN-LAST:event_lognoFocusLost

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      try
      {  
        int qtyy=Integer.parseInt(qty.getText());
        Connection con=MyConnection.createCon();
        PreparedStatement p=con.prepareStatement("select * from parts where part_no=?");
        PreparedStatement updateqty=con.prepareStatement("Update parts set avail_qty=? where part_no=?");
        p.setString(1, newpart.getText().trim());
        ResultSet rr=p.executeQuery();
        if(!rr.next())
            throw new Exception("No such part available");
        int avail;
        if((avail=Integer.parseInt(rr.getString(3)))<qtyy)
            throw new Exception("Available quantity is "+avail+" only");
        updateqty.setString(1, (avail-qtyy)+"");
        updateqty.setString(2, newpart.getText().trim());
       PreparedStatement st=null;
        if(add.getText().equals("Add"))
        {
          st=con.prepareStatement("insert into partsused values(?,?,?)");
          st.setString(1, logno.getText().trim());
          st.setString(2,newpart.getText().trim());
          st.setInt(3, Integer.parseInt(qty.getText().trim()));
          int rows=st.executeUpdate();
          if(rows==0)
             throw new Exception("failed");
          else 
          {
              tm.addRow(new Object[]{newpart.getText().trim(),qty.getText().trim()});
              JOptionPane.showMessageDialog(null,"Added");
              updateqty.executeUpdate();
          }
        }
        else
        {
            int i=table1.getSelectedRow();
            st=con.prepareStatement("update partsused set part_no=?,qty=? where log_no=? and part_no=? and qty=?");
            st.setString(1, newpart.getText().trim());
            st.setString(2, qty.getText().trim());
            st.setString(3, logno.getText().trim());
            st.setString(4, tm.getValueAt(i, 0).toString());
            st.setString(5, tm.getValueAt(i, 1).toString());
           int rows=st.executeUpdate();
           if(rows==0)
           {
               throw new Exception("Update Failed!!");
           }
           JOptionPane.showMessageDialog(null, "Updated!");
           
           tm.setValueAt(newpart.getText(), i, 0);
           tm.setValueAt(qty.getText(), i, 1);
        }
              }
      catch(Exception e)
      {
          if(e.getMessage().substring(0, 6).equals("Cannot"))
              JOptionPane.showMessageDialog(null, "Invalid Values");
          else
             JOptionPane.showMessageDialog(null,e.getMessage()); 
      }// TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void mtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtypeActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintenanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintenanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintenanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintenanceDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               MaintenanceDetails md= new MaintenanceDetails();
                       md.setSize(830, 550);
                       md.setLocationRelativeTo(null);
                       md.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel added;
    private javax.swing.JRadioButton addnew;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup btngrp;
    private javax.swing.JButton delrec;
    private javax.swing.JButton delrow;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loggedin;
    private javax.swing.JTextField logno;
    private javax.swing.JTextField mtype;
    private javax.swing.JTextField newpart;
    private javax.swing.JTextField qty;
    private javax.swing.JButton search;
    private javax.swing.JTextField staffid;
    private javax.swing.JTable table1;
    private javax.swing.JRadioButton update;
    // End of variables declaration//GEN-END:variables
}
