
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class TripCompletion extends javax.swing.JFrame {
        String username;
    /**
     * Creates new form TripCompletion
     */
    public TripCompletion() {
        initComponents();
        alert.setText("");
        staffid1.setEnabled(false);
        sodo1.setEnabled(false);
        eodo1.setEnabled(false);
        fuel.setEnabled(false);
        cc1.setEnabled(false);
        complaints1.setEnabled(false);
        update.setEnabled(false);
        vno1.setEnabled(false);
        del.setAlignmentX(CENTER_ALIGNMENT);
        vno.setEnabled(false);
        staffid.setEnabled(false);
       
    }
    
      public TripCompletion(String s){
       
        initComponents();
         alert.setText("");
        staffid1.setEnabled(false);
        sodo1.setEnabled(false);
        eodo1.setEnabled(false);
        fuel.setEnabled(false);
        cc1.setEnabled(false);
        complaints1.setEnabled(false);
        update.setEnabled(false);
         vno1.setEnabled(false);
        username=s;
        loggedin.setText(loggedin.getText()+username);
        del.setAlignmentX(CENTER_ALIGNMENT);
        vno.setEnabled(false);
        staffid.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loggedin = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resno = new javax.swing.JTextField();
        staffid = new javax.swing.JTextField();
        vno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaints = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sodo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eodo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fuel1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vno1 = new javax.swing.JTextField();
        cc1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        complaints1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        resno1 = new javax.swing.JTextField();
        sodo1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        staffid1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        eodo1 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fuel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        delres = new javax.swing.JTextField();
        del = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel1.setText("TRIP COPMLETION");

        loggedin.setText("Logged In As:");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Reservation Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 52, -1, -1));

        resno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                resnoFocusLost(evt);
            }
        });
        jPanel1.add(resno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 121, -1));

        staffid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffidActionPerformed(evt);
            }
        });
        jPanel1.add(staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 96, 121, -1));
        jPanel1.add(vno, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 141, 121, -1));

        jLabel3.setText("Staff ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 96, 98, -1));

        jLabel4.setText("Vehicle Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 144, 98, -1));
        jPanel1.add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 184, 121, -1));

        jLabel5.setText("Credit Card");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 187, 98, -1));

        jLabel7.setText("Complaints:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        complaints.setColumns(20);
        complaints.setRows(5);
        jScrollPane1.setViewportView(complaints);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 273, 224));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 293, 130, 30));

        jLabel8.setText("Start Odometer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        jPanel1.add(sodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 121, -1));

        jLabel9.setText("End Odometer");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 327, -1, -1));

        eodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eodoActionPerformed(evt);
            }
        });
        jPanel1.add(eodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 327, 121, -1));

        jLabel20.setText("Fuel");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        fuel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuel1ActionPerformed(evt);
            }
        });
        jPanel1.add(fuel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 121, -1));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 20));

        alert.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 30, 20));

        jTabbedPane1.addTab("Complete Reservation", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("jLabel6");
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 0, 280));

        jLabel11.setText("Staff ID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 98, -1));

        vno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vno1ActionPerformed(evt);
            }
        });
        jPanel2.add(vno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 144, 120, -1));
        jPanel2.add(cc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 190, 120, -1));

        jLabel12.setText("Credit Card");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 98, -1));

        complaints1.setColumns(20);
        complaints1.setRows(5);
        jScrollPane2.setViewportView(complaints1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 43, 273, 224));

        jLabel13.setText("Reservation Number");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        resno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resno1ActionPerformed(evt);
            }
        });
        jPanel2.add(resno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 121, -1));
        jPanel2.add(sodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 121, -1));

        jLabel14.setText("Start Odometer");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        staffid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffid1ActionPerformed(evt);
            }
        });
        jPanel2.add(staffid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, -1));

        jLabel15.setText("Vehicle Number");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 147, 98, -1));

        jLabel16.setText("End Odometer");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        eodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eodo1ActionPerformed(evt);
            }
        });
        jPanel2.add(eodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 121, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel17.setText("Complaints:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 27, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("jLabel6");
        jLabel18.setOpaque(true);
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 20, 0, 290));

        jLabel21.setText("Fuel");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel2.add(fuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, -1));

        jTabbedPane1.addTab("Edit Completed Reservation", jPanel2);

        jLabel19.setText("Reservation Number");

        del.setFont(new java.awt.Font("Sylfaen", 0, 48)); // NOI18N

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(73, 73, 73)
                .addComponent(delres, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(delres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("Delete", jPanel3);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(176, 176, 176)
                        .addComponent(loggedin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(back)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(loggedin))
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eodoActionPerformed

    private void eodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eodo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eodo1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
        {
             if(Integer.parseInt(eodo.getText())<Integer.parseInt(sodo.getText()))
                throw new Exception("End Odometer should be greater than Start Odometer");
            Connection c=MyConnection.createCon();
            PreparedStatement p=c.prepareStatement("insert into tripcompletion values(?,?,?,?,?,?,?,?)");
            p.setString(1, resno.getText().trim());
            p.setString(2, staffid.getText().trim());
            p.setString(3, vno.getText().trim());
            p.setString(4, cc.getText().trim());
            p.setFloat(5, Float.parseFloat(fuel1.getText().trim()));
            p.setString(6, sodo.getText().trim());
            p.setString(7, eodo.getText().trim());
            p.setString(8, complaints.getText().trim());
            int rows=p.executeUpdate();
            if(rows==0)
              throw new Exception("Failed!");
            else
              JOptionPane.showMessageDialog(null,"Done!!");
            
        }
        catch(Exception e)
        {
            if(e.getMessage().substring(0, 6).equals("Cannot"))
              JOptionPane.showMessageDialog(null, "Enter Valid Reservation Number");
            else
            JOptionPane.showMessageDialog(null, e.getMessage());
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void staffidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffidActionPerformed

    private void fuel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuel1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       try
      {
          Connection cc=MyConnection.createCon();
            PreparedStatement st=cc.prepareStatement("select * from tripcompletion where res_no=?;");
            st.setString(1, resno1.getText().trim());
            ResultSet res=st.executeQuery();
            if(res.next()==false)
            throw new Exception("Not found!!"); 
            
            sodo1.setEnabled(true);
            eodo1.setEnabled(true);
            fuel.setEnabled(true);
            cc1.setEnabled(true);
            complaints1.setEnabled(true);
            update.setEnabled(true);
            staffid1.setText(res.getString(2));
            vno1.setText(res.getString(3));
            fuel.setText(res.getString(5));
            cc1.setText(res.getString(4));
            sodo1.setText(res.getString(6));
            eodo1.setText(res.getString(7));
            complaints1.setText(res.getString(8));
     }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       try
        {
            if(Integer.parseInt(eodo1.getText())<Integer.parseInt(sodo1.getText()))
                throw new Exception("End Odometer should be greater than Start Odometer");
            Connection c=MyConnection.createCon();
            PreparedStatement p=c.prepareStatement("update tripcompletion set credit_card=?,fuel=?, s_odo=?, e_odo=?,complaints=? where res_no=?");
            p.setString(2,fuel.getText());
            p.setString(1,cc1.getText());
            p.setString(3,sodo1.getText());
            p.setString(4,eodo1.getText());
            p.setString(5,complaints1.getText());
            p.setString(6,resno1.getText());
            
            int rows=p.executeUpdate();
            if(rows==0)
            throw new Exception("Failed!");
            else
            JOptionPane.showMessageDialog(null,"Updated" );
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try
        {
            Connection c=MyConnection.createCon();
            PreparedStatement p1=c.prepareStatement("select * from tripcompletion where res_no=?");
            p1.setString(1, delres.getText().trim());
            ResultSet rr=p1.executeQuery();
            if(rr.next()==false)
            throw new Exception("Not Found!!");
            PreparedStatement p=c.prepareStatement("delete from  tripcompletion where res_no=?");
            p.setString(1, delres.getText().trim());
            int rows=p.executeUpdate();
            if(rows==0)
            throw new Exception("Failed!");
            else
            del.setText("Deleted!!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       Homepage hm=new Homepage(username);
              hm.setLocationRelativeTo(null);
              hm.setVisible(true);
              dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void resnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resnoFocusLost
      try
        {
            alert.setText("");
            Connection c=MyConnection.createCon();
            PreparedStatement p1=c.prepareStatement("select staff_id,v_no from reservation where res_no=?");
            p1.setString(1, resno.getText().trim());
            ResultSet rr=p1.executeQuery();
            if(rr.next()==false)
                throw new Alert();
            
           staffid.setText(rr.getString(1));
           vno.setText(rr.getString(2));
           
           
        }
      
       catch(Alert e)
        {
            staffid.setText("");
            alert.setText("invalid");
        } 
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }   // TODO add your handling code here:
    }//GEN-LAST:event_resnoFocusLost

    private void vno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vno1ActionPerformed

    private void resno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resno1ActionPerformed

    private void staffid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffid1ActionPerformed

    private void resnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resnoFocusGained
       alert.setText("");
       // TODO add your handling code here:
    }//GEN-LAST:event_resnoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TripCompletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TripCompletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TripCompletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TripCompletion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TripCompletion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JButton back;
    private javax.swing.JTextField cc;
    private javax.swing.JTextField cc1;
    private javax.swing.JTextArea complaints;
    private javax.swing.JTextArea complaints1;
    private javax.swing.JLabel del;
    private javax.swing.JButton delete;
    private javax.swing.JTextField delres;
    private javax.swing.JTextField eodo;
    private javax.swing.JTextField eodo1;
    private javax.swing.JTextField fuel;
    private javax.swing.JTextField fuel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel loggedin;
    private javax.swing.JTextField resno;
    private javax.swing.JTextField resno1;
    private javax.swing.JButton search;
    private javax.swing.JTextField sodo;
    private javax.swing.JTextField sodo1;
    private javax.swing.JTextField staffid;
    private javax.swing.JTextField staffid1;
    private javax.swing.JButton update;
    private javax.swing.JTextField vno;
    private javax.swing.JTextField vno1;
    // End of variables declaration//GEN-END:variables
}
